{"detail":"SadTalker Inferenz fehlgeschlagen (rc=1):\n\nlandmark Det::   0%|          | 0/1 [00:00<?, ?it/s]\nlandmark Det:: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]\nlandmark Det:: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]\n\n3DMM Extraction In Video::   0%|          | 0/1 [00:00<?, ?it/s]\n3DMM Extraction In Video::   0%|          | 0/1 [00:00<?, ?it/s]\nTraceback (most recent call last):\n  File \"/Users/hhsw/Desktop/sunriza26/SadTalker/inference.py\", line 144, in <module>\n    main(args)\n  File \"/Users/hhsw/Desktop/sunriza26/SadTalker/inference.py\", line 46, in main\n    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess,\\\n                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hhsw/Desktop/sunriza26/SadTalker/src/utils/preprocess.py\", line 146, in generate\n    trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std)\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hhsw/Desktop/sunriza26/SadTalker/src/face3d/util/preprocess.py\", line 101, in align_img\n    trans_params = np.array([w0, h0, s, t[0], t[1]])\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part."}